### PR TITLE
Rework learn command to allow for wildcard docs

### PR DESCRIPTION
**Pull request by microlith57**
Quite a big change.

Changelog:

- Reworked wildcards to allow for `[name, [inputs], description]` format
- Reworked the learn command to allow for a more fluid learning experience with all documentation viewable
- Allow for all learnable items to be listed entirely in the learn command

In summary, all documentation is now available in the learn command - for actions, wildcards, wildcard groups, and general knowledge.

### CODE REVIEW

**Comment by neauoire** [comment]
wow, huh.
Give me a moment to test this out :)

**Comment by microlith57** [comment]
To do this, I basically threw out all your `learn` code, so some things might work differently. There could be bugs, I haven't quite finished testing.

But so far it seems to work well other than a bit of weird `<br />` spacing on the desktop client.

**Comment by microlith57** [comment]
I've done some more testing, and I think it works fine now.

:)

**Comment by microlith57** [comment]
Looks like I accidentally included this functionality in another PR. Closing...

**Pull request closed without merging**
