### PR TITLE
Various typographical changes, and re-created the (missing) inventory command

### PR DESCRIPTION
**Pull request by microlith57**
The `look` command is now dynamic, and has a configurable upper limit for the number of observed vessels. It now also has configuration for [Oxford Comma](https://en.wikipedia.org/wiki/Serial_comma) (a comma before 'and').

This should have identical behaviour to the old `look` command, other than Oxford Comma being on by default now, and an increase in the default number of visible vessels (from 3 to 5).

### CODE REVIEW

**Comment by microlith57** [comment]
Also recreated the `inventory` command, which disappeared somehow. This uses a similar style to my `look`, but does not have an upper limit for visible vessels.

See also #8

**Comment by microlith57** [comment]
Now also fixed several minor typographical errors:

- Inspect now always uses the `the` particle
- `vessel.particle()` always returns `a` or `an` - never `the`
- `create` now works correctly when dealing with vowels

**Comment by microlith57** [comment]
Massively overhauled the `look` command such that it increases in brevity as the number of visible vessels increases.

This change requires the `pluralise` library.

**Comment by neauoire** [comment]
Oh wow, I will look at all of this in the morning!

**Comment by microlith57** [comment]
Thank you!

**Comment by neauoire** [comment]
This works amazingly! I will push to master :)
Thank you so much!

**Comment by microlith57** [comment]
Thank you so much!

I am considering adding a `@error` wildcard too, to make things such as a coffee machine that `transform`s cups into coffee cups, and states whether or not a cup was filled:
```
use coffee machine
[The cup is already full]
use cup
[You drink the coffee]
use coffee machine
[The cup fills with coffee]
```
Of course, this is still in the works. I will hopefully get back to you soon!

**Comment by neauoire** [comment]
I'd merge that :) I've been thinking it would be nice to expand the default world to show some of these examples.

**Pull request merged**
