### PR TITLE
Lots of wildcards!

### PR DESCRIPTION
**Pull request by microlith57**
I have added a _lot_ of wildcards and wildcard-related features. I think this will make WildcardLISP scripting much more flexible.

Changelog:

- Overhaul some documentation, and update it for the below changes
- Add a coffee machine example
- Add a `@(success)` wildcard and an `@(error)` wildcard
- Make vessels remember the error raised (or null) of their previous command
- Add lots of arithmetic commands
- Add a `nil` datatype to WildcardLISP
- Add logic operators (and / or) that use `nil` as a falsey value and everything else as truthey
- Add a `@(tc)` command that makes things titlecase (eg. 'The Ceramic Library')
- Add a `@(concat)` command to concatenate strings
- Add some items to TODO.md and adjust / remove the old ones as necessary
- Fix a bug where `require()` would silently fail to find commands if an error occurred while loading. This now crashes (as it should).
- Update `.gitignore` to ignore logs and various other things that should be ignored
- Move helper functions etc. into `helpers.js`
- Move errors to `errors.js` and the Error class to `error.js`
- Add wildcards for `siblings` and `children` - they return lists of IDs
- Add a `map` wildcard to run lambdas over lists
- Add a lot of list utilities

All in all, a lot of stuff. The YAML format requires another dependency, `js-yaml`, but it is very small.

### CODE REVIEW

**Comment by neauoire** [comment]
I have just tested it and everything seems to work amazingly!
There's only one thing, I would prefer if we didn't use YAML. I'd like to only have json support.

Would it be alright for you to remove this part?

**Comment by microlith57** [comment]
That's fine. Personally, I quite YAML for editing, but I can remove it if you think it's out of scope.

Would it be OK for me to make a small conversion utility for editing purposes?

**Comment by microlith57** [comment]
YAML support is now removed.

**Comment by neauoire** [comment]
Go ahead with a converter, but don't include any more external scripts in the project :)

**Comment by neauoire** [comment]
Do you run the `walkthrough()` tester? I think a lot of these new toys should be added to the walkthrough to help with testing :)

**Comment by neauoire** [comment]
This PR is nuts haha.

**Comment by microlith57** [comment]
I didn't even know that existed! I have found and used it, and all seems to be well in my latest branch (lots of fun coming soon). I think I will arrange for it to save the current world beforehand and restore it afterwards - in custom worlds it can be a bit wonky. I also think it would be a good idea to reset the world before starting each walkthrough segment.

Time to start another feature branch!

**Pull request merged**
