### PR TITLE
add simple "inventory" command to view what we are currently carrying

### PR DESCRIPTION
**Pull request by ghost**
It just displays all the vessels the current vessel is carrying by typing "inventory". Like so:
inventory

EDIT:
Clicking any of them auto inserts "drop the <vessel name>"

### CODE REVIEW

**Comment by neauoire** [comment]
Excellent, very useful : )

**Comment by neauoire** [comment]
screen shot 2018-05-02 at 10 09 24 am

I've implemented an inventory UI.

**Comment by ghost** [comment]
That is even better!

**Comment by neauoire** [comment]
I'll keep the `inventory` action tho. It's always nice to be able to play without a mouse.

**Comment by ghost** [comment]
Yeah I personally prefer that

**Comment by neauoire** [comment]
Released the **inventory** update to itch/master!

**Comment by ghost** [comment]
Is it already available for download from the itch.io page?

**Comment by neauoire** [comment]
If you're using Paradise through the itch client, it should automatically update it.
It handle file changes, so it only download the changed ones, making for very small updates.

**Comment by ghost** [comment]
I am not getting any update when running the executable. Is it supposed to download it?

**Comment by neauoire** [comment]
If you simply downloaded a zip file from the project's page on itch, it won't down it automatically.

Otherwise, it should have done something like this:

screen shot 2018-05-02 at 10 33 03 am

**Comment by neauoire** [comment]
before:
screen shot 2018-05-02 at 10 34 41 am

after:
screen shot 2018-05-02 at 10 35 51 am

**Comment by ghost** [comment]
Ah I see. I got the .zip version so thats why. I don't have the itch.io app so now I understand. The inventory rocks now, thanks a bunch!

**Comment by neauoire** [comment]
Thanks to you 👍

**Pull request merged**
